name: EGlance Build

# Only included into other workflows
on:
  workflow_call:

jobs:
  get_default_envs:
    name: Gather Environments
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install pio and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Get default environments
        id: envs
        run: |
          echo "environments=$(pio project config --json-output | jq -cr '.[0][1][0][1]')" >> $GITHUB_OUTPUT
    outputs:
      environments: ${{ steps.envs.outputs.environments }}

  release:
    runs-on: ubuntu-latest
    needs: get_default_envs
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.get_default_envs.outputs.environments) }}
    steps:
      - uses: actions/checkout@v2
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio/.cache
            ~/.buildcache
          key: pio-${{ runner.os }}-${{ matrix.environment }}-${{ hashFiles('platformio.ini', 'extra_script.py') }}
          restore-keys: pio-${{ runner.os }}-${{ matrix.environment }}-${{ hashFiles('platformio.ini', 'extra_script.py') }}
      - name: Set up Python
        uses: actions/setup-python@v1

      - name: Install pio and its dependencies
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      - name: Run PlatformIO build on selected platforms
        run: pio run -e ${{ matrix.environment }}

      - name: Upload binaries to release
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.environment }}
          path: |
            .pio/build/*/firmware_*.bin
